#服务名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        #这里填写你自己的git项目路径，用户名密码
        git:
          uri: https://github.com/hushuna/zhiliao_config
          username:
          password:
          timeout: 5
          default-label: master

#服务的端口号
server:
  port: 1014

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://101.132.144.61:1010/eureka/
